services:
  db:
    image: postgres:14-alpine
    ports:
      - '5433:5432'

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}

    volumes:
      - ./data/db:/var/lib/postgresql/data/

    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_db.local
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

    command: sh -c "npm install && npm run dev"

    ports:
      - '3000:3000'

    volumes:
      - ./frontend:/app/frontend
      - node_modules:/app/frontend/node_modules

    depends_on:
      - backend

    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_react.local

  backend: 
    build: 
      context: ./backend
      dockerfile: Dockerfile

    env_file:
      - ./backend/.env

    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db

    ports:
      - '8000:8000'

    volumes:
      - ./backend:/app/backend
      - ./static:/app/backend/staticfiles
      - ./gcs-credentials.json:/app/gcs-credentials.json

    depends_on:
      db:
        condition: service_healthy
      
    networks:
      custom_network:
        aliases:
          - ${PROJECT_NAME}_django.local


  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - custom_network

  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: celery -A config worker --loglevel=info --concurrency=2
    env_file:
      - ./backend/.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - DATABASE_HOST=db
    volumes:
      - ./backend:/app/backend
      - ./gcs-credentials.json:/app/gcs-credentials.json
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - custom_network

networks:
  custom_network:
    name: ${PROJECT_NAME}
    driver: bridge


volumes:
  node_modules:
    driver: local
