FROM python:3.12-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app/backend

COPY requirements/base.txt .
COPY requirements/production.txt .

RUN apk update && \
    apk add --no-cache \
    build-base \
    linux-headers \
    postgresql-dev \
    python3-dev \
    postgresql-client \
    libmagic \
    libffi-dev && \
    pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir -r production.txt

COPY . .

COPY entrypoint.prod.sh /entrypoint.prod.sh
RUN sed -i 's/\r$//' /entrypoint.prod.sh && chmod +x /entrypoint.prod.sh

ENTRYPOINT ["/entrypoint.prod.sh"]
