# Generated by Django 6.0.2 on 2026-05-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('forum_answer', 'Someone answered your question'), ('forum_comment', 'Someone replied to your answer'), ('assignment_created', 'A new assignment was posted'), ('assignment_graded', 'Your submission was graded'), ('assignment_reviewed', 'Your submission received a review'), ('submission_commented', 'Someone commented on your submission')], max_length=32),
        ),
    ]
