# Generated by Django 6.0.2 on 2026-03-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EsiProfessor',
            fields=[
                ('school_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('grade', models.CharField(choices=[('MAB', 'Maître-Assistant B'), ('MCA', 'Maître de Conférences A'), ('MCB', 'Maître de Conférences B'), ('PR', 'Professeur')], max_length=10)),
                ('status', models.CharField(choices=[('permanent', 'Permanent'), ('adjunct', 'Adjunct')], default='permanent', max_length=20)),
            ],
            options={
                'db_table': 'esi_professors',
            },
        ),
        migrations.CreateModel(
            name='EsiStudent',
            fields=[
                ('school_id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('section', models.CharField(blank=True, help_text='A/B/C.. for 1CP-1CS, SIQA/SIQB/SITA/SITB... for 2CS and 3CS, null for alumni', max_length=4, null=True)),
                ('group', models.IntegerField(blank=True, null=True)),
                ('study_year', models.CharField(blank=True, choices=[('1CP', '1ère année cycle préparatoire'), ('2CP', '2ème année cycle préparatoire'), ('1CS', '1ère année cycle supérieur'), ('2CS', '2ème année cycle supérieur'), ('3CS', '3ème année cycle supérieur')], max_length=3, null=True)),
                ('status', models.CharField(choices=[('inscrit', 'Inscrit'), ('abandon', 'Abandon'), ('alumni', 'Alumni')], default='inscrit', max_length=20)),
            ],
            options={
                'db_table': 'esi_students',
            },
        ),
    ]
