# Generated by Django 6.0.2 on 2026-03-25 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esi_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='esistudent',
            name='section',
            field=models.CharField(blank=True, help_text='A/B... for 1CP-1CS, SIQA/SIQB/SITA... for 2CS and 3CS, null for alumni', max_length=4, null=True),
        ),
    ]
