# Generated by Django 6.0.2 on 2026-04-01 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_drop_legacy_username_column'),
        ('assignment_submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('target_year__in', ['1CP', '2CP', '1CS', '2CS', '3CS'])), name='assignment_target_year_valid'),
        ),
    ]
