# Generated by Django 6.0.2 on 2026-04-23 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_submissions', '0002_assignment_assignment_target_year_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of programming languages for this assignment. e.g. ["python", "c"]'),
        ),
    ]
