# Generated by Django 6.0.2 on 2026-05-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_submissions', '0003_assignment_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='description_pdf',
            field=models.CharField(blank=True, help_text='GCS path to the assignment description PDF file.', max_length=500, null=True),
        ),
    ]
