# Generated by Django 6.0.2 on 2026-05-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='public_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
