# Generated by Django 6.0.2 on 2026-05-09 23:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_populate_user_public_id'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="SELECT 1",  # constraint already exists, do nothing
                    reverse_sql="DROP INDEX IF EXISTS accounts_user_public_id_a3014eda_uniq",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='user',
                    name='public_id',
                    field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
                ),
            ],
        ),
    ]

