# Generated by Django 6.0.2 on 2026-05-04 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProblemReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('bug', 'Bug / something is broken'), ('ui_issue', 'UI / display issue'), ('wrong_data', 'Wrong or missing data'), ('missing_feature', 'Missing feature or suggestion'), ('other', 'Other')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('page_url', models.CharField(blank=True, help_text='The page path where the problem occurred (e.g. /forum/12).', max_length=500)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note visible only in admin — not shown to users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problem_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Problem Report',
                'verbose_name_plural': 'Problem Reports',
                'db_table': 'problem_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('spam', 'Spam or irrelevant content'), ('harassment', 'Harassment or bullying'), ('impersonation', 'Impersonation'), ('academic_dishonesty', 'Academic dishonesty'), ('other', 'Other')], max_length=32)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('status', models.CharField(choices=[('open', 'Open'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='open', max_length=16)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note visible only in admin — not shown to users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_received', to=settings.AUTH_USER_MODEL)),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Report',
                'verbose_name_plural': 'User Reports',
                'db_table': 'user_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
