# Generated by Django 6.0.2 on 2026-05-09 09:19

from django.db import migrations


def seed_subject_tags(apps, _schema_editor):
    Subject = apps.get_model('accounts', 'Subject')
    Tag = apps.get_model('forum', 'Tag')

    for subject in Subject.objects.all():
        Tag.objects.get_or_create(
            name=subject.name.strip().lower()[:50],
            defaults={'is_subject': True},
        )


def reverse_seed(apps, _schema_editor):
    Tag = apps.get_model('forum', 'Tag')
    Tag.objects.filter(is_subject=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_tag_remove_question_tags_question_tags'),
        ('accounts', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.RunPython(seed_subject_tags, reverse_code=reverse_seed),
    ]