# Generated by Django 6.0.2 on 2026-04-23 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignment_submissions', '0003_assignment_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlagiarismReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('complete', 'Complete'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('moss_urls', models.JSONField(blank=True, default=dict)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='plagiarism_report', to='assignment_submissions.assignment')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'plagiarism_reports',
            },
        ),
        migrations.CreateModel(
            name='SimilarityMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('similarity_a', models.IntegerField()),
                ('similarity_b', models.IntegerField()),
                ('lines_matched', models.IntegerField()),
                ('moss_link', models.URLField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='plagiarism.plagiarismreport')),
                ('submission_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_matches_as_a', to='assignment_submissions.assignmentsubmission')),
                ('submission_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarity_matches_as_b', to='assignment_submissions.assignmentsubmission')),
            ],
            options={
                'db_table': 'similarity_matches',
            },
        ),
    ]
