# Generated by Django 6.0.2 on 2026-04-25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='similaritymatch',
            name='lines_matched',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='similaritymatch',
            name='similarity_a',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='similaritymatch',
            name='similarity_b',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddConstraint(
            model_name='similaritymatch',
            constraint=models.CheckConstraint(
                condition=models.Q(submission_a__lt=models.F('submission_b')),
                name='similarity_match_submission_order',
            ),
        ),
        migrations.AddConstraint(
            model_name='similaritymatch',
            constraint=models.CheckConstraint(
                condition=models.Q(similarity_a__lte=100),
                name='similarity_a_lte_100',
            ),
        ),
        migrations.AddConstraint(
            model_name='similaritymatch',
            constraint=models.CheckConstraint(
                condition=models.Q(similarity_b__lte=100),
                name='similarity_b_lte_100',
            ),
        ),
        migrations.AddConstraint(
            model_name='similaritymatch',
            constraint=models.UniqueConstraint(
                fields=('report', 'submission_a', 'submission_b', 'language'),
                name='unique_similarity_pair_per_language',
            ),
        ),
    ]
