# Generated by Django 6.0.2 on 2026-04-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_submissions', '0003_assignment_languages'),
        ('plagiarism', '0002_similaritymatch_hardening'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIReferenceSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50)),
                ('style', models.CharField(max_length=50)),
                ('gcs_path', models.CharField(max_length=1000)),
                ('file_name', models.CharField(max_length=255)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_references', to='assignment_submissions.assignment')),
            ],
            options={
                'db_table': 'ai_reference_submissions',
            },
        ),
    ]
