# Generated by Django 6.0.2 on 2026-05-01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plagiarism', '0003_aireferencesubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='similaritymatch',
            name='ai_moss_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='similaritymatch',
            name='submission_a',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='similarity_matches_as_a',
                to='assignment_submissions.assignmentsubmission',
            ),
        ),
        migrations.AlterField(
            model_name='similaritymatch',
            name='submission_b',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='similarity_matches_as_b',
                to='assignment_submissions.assignmentsubmission',
            ),
        ),
    ]
