# Generated by Django 6.0.2 on 2026-05-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plagiarism", "0004_similaritymatch_ai_moss_flag"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="similaritymatch",
            name="unique_similarity_pair_per_language",
        ),
        migrations.AddConstraint(
            model_name="similaritymatch",
            constraint=models.UniqueConstraint(
                fields=["report", "submission_a", "submission_b", "language"],
                condition=models.Q(ai_moss_flag=False),
                name="unique_similarity_pair_per_language",
            ),
        ),
    ]
